export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_FAILURE = "PRODUCT_FAILURE"
export const POST_PRODUCT_SUCESS = "POST_PRODUCT_SUCESS"
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGIN_SUCESS = "LOGIN_SUCESS"